"""empty message

Revision ID: f5bdd0b7f97d
Revises: 676cde3d958c
Create Date: 2022-04-04 12:26:48.566990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5bdd0b7f97d'
down_revision = '676cde3d958c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planets_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicles_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='favorites_ibfk_1'),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], name='favorites_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_ibfk_3'),
    sa.ForeignKeyConstraint(['vehicles_id'], ['vehicles.id'], name='favorites_ibfk_4'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('favorite_planets')
    op.drop_table('favorite_people')
    # ### end Alembic commands ###
